= GraphQL server benchmark

Benchmark of a simple https://graphql.org/[GraphQL] server on popular spec implementations.

== Lastest results

TBD

== The benchmark

The benchmark consists in a simple blogging GraphQL server:

- reading rows (posts and comments) from a Postgres database
- fetching json (author profiles) from a remote HTTP server

image::graphql-server-benchmark.svg[GraphQL Server Banchmark]

[source]
.Schema file
----
type Post {
    author: Author!
    title: String!
    content: String!
    comments: [Comment!]
}

type Comment {
    id: ID!
    author: Author!
    content: String!
}

type Author {
    firstName: String!
    lastName: String!
    bio: String!
    posts: [Post!]
}

type Query {
    author(id: Int!): Author
}
----

== Guidelines

The server may:
- cache GraphQL query parsing result
- cache author profiles per-query

The server must not:
- cache all posts and comments
- cache all author profiles

== Test environment

- 3 servers Intel Xeon e5-2637v3 128G RAM (injector, server, backend)
- 1 server Intel Xeon e5-2637v3 256G RAM (postgres)
- 10 GbE switch

== Contributing

You can add an implementation in the link:implementations/[implementations] directory.

Make sure the name describes the software stack.
For example, _java_vertx_graphql-java_ means the implementation:

* is written in the Java language
* uses Vert.x as the web server
* uses GraphQL-Java engine

Each implementation must provide a `Dockerfile` (build and run).

For testing purposes, you can build an run with Docker:

* the link:backend/[backend] server
* the link:postgres/[postgres] database

== License

link:LICENSE[Apache 2.0 License]